### ISSUE TITLE
Exception calling "AcquireToken" with "3" argument(s)

### ISSUE THREAD

**Issue by dodgy99** [maikvandergaag/msft-extensions#111]
Hi,

We have recently been getting the following error message when using this extension, it has been working perfectly for months before this:

Exception calling "AcquireToken" with "3" argument(s): "accessing_ws_metadata_exchange_failed: Accessing WS metadata exchange failed"

Please can you advise?

Thanks

**Comment by maikvandergaag** [comment]
hi,

is the application configuration still valid and can you still login with the account you are using?

**Comment by dodgy99** [comment]
Hi,

Thanks for the response, as far as we can tell everything is ok from both an application config and yes we have no problems logging in with the account being used for deployments. 

Looks to me like its failing AAD authentication but I cant find the reason why.

I will keep looking, but the issue must lie either with user permissions (not that I can see), a service issue with AAD, or the method AcquireToken used to authenticate may have changed.

I'm stabbing in the dark just guessing at the moment.

Thanks

**Comment by maikvandergaag** [comment]
You are the first to encounter this issue. From our side nothing changed with the authentication.

What you could try if possible is to start with a clean configuration and see if the problem is solved with a new account / application. 

And besides that you can check if the account can do the same things that you want to do with the extension in the interface. If it does that is not the problem and make sure MFA is disabled for the account

**Comment by dodgy99** [comment]
It seems to fail in different places along the release pipeline and very occasionally (perhaps 1 in 20) actually succeeds. Seems like the authentication is timing out or getting stuck so I'll follow it up.

Thanks for your help, I'll post back here if I find a reason. I'll close this for now.
