### ISSUE TITLE
Getting error when trying to use the update gateway using master account

### ISSUE THREAD

**Issue by AmalJacob1** [maikvandergaag/msft-extensions#248]
Am trying to change my gateway using Master account approach as it seems SPN authentication is not supported for gateway changes.
Am using an user which is not part of MFA but still am getting the below error when running the task.
Could you please help? 

Error
"AADSTS50079: Due to a configuration change made by your administrator, or because you moved to a new location, you must enroll in multi-factor authentication to access"

**Comment by maikvandergaag** [comment]
What happens when you try to login with this account in the browser?

Groetjes,

Maik van der Gaag
________________________________
Van: AmalJacob1 <notifications@github.com>
Verzonden: Monday, December 21, 2020 10:58:00 AM
Aan: maikvandergaag/msft-extensions <msft-extensions@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [maikvandergaag/msft-extensions] Getting error when trying to use the update gateway using master account (#248)


Am trying to change my gateway using Master account approach as it seems SPN authentication is not supported for gateway changes.
Am using an user which is not part of MFA but still am getting the below error when running the task.
Could you please help?

Error
"AADSTS50079: Due to a configuration change made by your administrator, or because you moved to a new location, you must enroll in multi-factor authentication to access"

**Comment by AmalJacob1** [comment]
It is getting logged in fine using the user.

**Comment by AmalJacob1** [comment]
Or maybe could you share the powershell for logging into Power Bi service without MFA ( silent login ).

**Comment by AmalJacob1** [comment]
@maikvandergaag > 
I got the master account service connection working now
Now with the master account connection, the task for dataset takeover and parameter update is working but for gateway update its giving me the error
"No gateway found! Ensure MasterAccount authentication is used and check if specified gateway 'XXX' is valid and present"

we have an oracle gateway named (1) XXX which maps to one gateway object (2)
Screenshot of how our gateway setting looks like
![image](https://user-images.githubusercontent.com/75451614/102823045-6ddc0780-43da-11eb-8a23-9ee47256c8a1.png)

In the update gateway task, for gateway name i gave the gateway name (1) as XXX but still it threw the above error. I tried giving gateway object (2) as well but also got the error
Should we give gateway id instead?  Could you please help, or show me a example on how to pass the gateway name/gateway object in the task?

I ran the power bi rest API command to fetch the available gateway details for the dataset
https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/discovergateways
The details looks like below, could you tell me which one to use

![image](https://user-images.githubusercontent.com/75451614/102821897-3e2c0000-43d8-11eb-9285-c388e34d6f81.png)

**Comment by maikvandergaag** [comment]
Internally we use this call: GET https://api.powerbi.com/v1.0/myorg/gateways.

Based on the name supplied we change the data. The problems that can occur in your situation is that the account you are using does not have the appropriate rights on the gateway.

**Comment by AmalJacob1** [comment]
What level of rights should the account have? Is it always admin?

**Comment by harmenverburg** [comment]
Isn't the issue that service principals cannot be added as admins to a gateway?

**Comment by maikvandergaag** [comment]
Yes that is it
