### ISSUE TITLE
Unable to refresh datasets due data source missing credentials

### ISSUE THREAD

**Issue by montstable** [maikvandergaag/msft-extensions#273]
Hello,

I wonder if you can help.  I've been spending a lot of time attempting to set up a Power BI CI/CD environment but I am stuck.  After I publish the datasets into the workspace and take control of them using a SPN account, I am unable to refresh the datasets manually or according to their schedule.  I have tried to update the gateway, to update the credentials using the SPN account but this fails.  I'm assuming this is because the SPN is not and cannot be added as an admin for the gateway?

I then try to take over the gateway using a non MFA user account but this also fails due to the following error:

AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance

I'm guessing that the user account is getting blocked somewhere, but my question is should we be using the SPN account to update the gateway or a user account?

The Azure App has all Power BI API permissions granted as well.

Thank you in advance for your help, really appreciated as I'm quite stuck!

**Comment by maikvandergaag** [comment]
The are some conditional access rules I place within your Azure Active Directory. I can not help with that you have to ask the guys that manage the aad

Groetjes,

Maik van der Gaag
________________________________
Van: montstable ***@***.***>
Verzonden: Thursday, April 1, 2021 3:01:31 PM
Aan: maikvandergaag/msft-extensions ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [maikvandergaag/msft-extensions] Unable to refresh datasets due data source missing credentials (#273)


Hello,

I wonder if you can help. I've been spending a lot of time attempting to set up a Power BI CI/CD environment but I am stuck. After I publish the datasets into the workspace and take control of them using a SPN account, I am unable to refresh the datasets manually or according to their schedule. I have tried to update the gateway, to update the credentials using the SPN account but this fails. I'm assuming this is because the SPN is not and cannot be added as an admin for the gateway?

I then try to take over the gateway using a non MFA user account but this also fails due to the following error:

AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance

I'm guessing that the user account is getting blocked somewhere, but my question is should we be using the SPN account to update the gateway or a user account?

The Azure App has all Power BI API permissions granted as well.

Thank you in advance for your help, really appreciated as I'm quite stuck!

**Comment by montstable** [comment]
That's great, thank you Maik, so just to confirm, to update the credentials to the gateway has to be a user account not the SPN?

**Comment by maikvandergaag** [comment]
Yes

Met vriendelijke groet,

Maik van der Gaag
