### ISSUE TITLE
update Apps via extension

### ISSUE THREAD

**Issue by mcharing** [maikvandergaag/msft-extensions#294]
Hi Maik,

I really like your extension and have automated much of the routine work. One thing that is missing for me is updating the Apps. MS has realised new functionally on that for Powershell with new cmdlets. Will your extension be including this functionality?

secondly; do I need to worry about this with your extension?; 
https://powerbi.microsoft.com/en-us/blog/heads-up-breaking-change-coming-to-power-bi-powershell-cmdlets/

**Comment by maikvandergaag** [comment]
@mcharing Will check the link you send me. Thanks for the heads up!

Regarding the apps could you maybe be more specific? What kind of actions you would prefer I can always look at the options.

**Comment by mcharing** [comment]
when I update the reports via a pipeline (over several workspaces at once 👍) I have to manually go to Power BI and for every workspace i need to update the App. This includes hitting 4 buttons per workspace to actually update the App. 

![update app (1)](https://user-images.githubusercontent.com/20912201/124113687-00392400-da6c-11eb-8de0-c0e1026c2bcf.png)
![update app (2)](https://user-images.githubusercontent.com/20912201/124113695-029b7e00-da6c-11eb-921a-6b3465a61670.png)
![update app (3)](https://user-images.githubusercontent.com/20912201/124113703-04fdd800-da6c-11eb-83f3-376713312efb.png)
![update app (4)](https://user-images.githubusercontent.com/20912201/124113711-07603200-da6c-11eb-9417-a8842367a7d1.png)

**Comment by maikvandergaag** [comment]
Oké, Will check what can be done

**Comment by mattias-de-coninck** [comment]
@mcharing If I understand correctly, you want the functionality to update the app in the Azure DevOps pipeline?
From my understanding, this will not be possible because of the following:

Power BI CmdLets: https://docs.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.workspaces/?view=powerbi-ps
   - There is no cmdlets that supports this functionality.

Power BI REST API: https://docs.microsoft.com/en-us/rest/api/power-bi/apps
   - There are only APIs available to fetch information regarding Apps, not update them.
   
 Is there something I am missing?

**Comment by maikvandergaag** [comment]
As there are no capabilities in the API / Cmdlets the issue will be closed for now
