### ISSUE TITLE
Error: Operation returned an invalid status code 'Forbidden'

### ISSUE THREAD

**Issue by joaovictormelo42** [maikvandergaag/msft-extensions#331]
Hi Maik, 

I closed the other issue i had opened, because that error has been solved, but i get this new one, and i don't know how to test it.

![image](https://user-images.githubusercontent.com/20947225/141114719-a95a2c4f-f59f-42c9-884f-a99e7eb9341a.png)

If you have some idea, please let me know.

**Comment by tmauro** [comment]
Wich action do you execute?

**Comment by tmauro** [comment]
I can reproduce the error:

$datasources = (Get-PowerBIDatasource -DatasetId $report.DatasetId -Scope Individual)

For me works if change the Scope to **Organization**
I'm using a service principal Power BI Admin

**Comment by sergeytrasko** [comment]
We are also experiencing the same issue - also using service principal.
The action used is 'Update SQL Credentials' 

Is there a way how to change Scope to Organization for this action through Azure DevOps? Or should we wait for new release of the extension?

**Comment by maikvandergaag** [comment]
I have added an option to choose the scope. That is now being deployed to the beta

**Comment by maikvandergaag** [comment]
Will be deployed later today to production. If that does not work please reopen the issue

**Comment by sergeytrasko** [comment]
@maikvandergaag Thanks for the fix.
I think there is another issue creeped in - https://github.com/maikvandergaag/msft-extensions/blob/main/azuredevops/powerbiactions-new/powerbiactionsnew/run.ps1#L85

I'm not a PowerShell expert but seems that "-eq" syntax should be used here. 
What do you think?

**Comment by maikvandergaag** [comment]
@sergeytrasko thanks for  seeing that totally used to C# programming fix is in the pipeline

**Comment by sergeytrasko** [comment]
I've add a PR to fix it #338

**Comment by sergeytrasko** [comment]
@maikvandergaag it seems that the issue is still there...
I've set Scope = Organization for UpdateSqlCreds action and still getting Forbidden.
From the logs I see that it is failing [on line 1016](https://github.com/maikvandergaag/msft-extensions/blob/main/azuredevops/powerbiactions-new/powerbiactionsnew/ps_modules/PowerBi/powerbi.psm1#L1016) - so I assume that Scope parameter was handled correctly.

The service principal we are using is added as Admin to the workspace, I tried both with standard and premium capacity workspaces - same result. In the same time other actions like 'Upload Power BI report' work fine using same service principal.

Do you have any other ideas?
