### ISSUE TITLE
Option to upload a pbix file as dashboard.

### ISSUE THREAD

**Issue by arnabdasgupta04** [maikvandergaag/msft-extensions#343]
@maikvandergaag  while using upload powerbi report , it is uploading only the report and dataset but not the dashboard , also I am not getting a separate option for uploading power bi dashboard in it , please assist me.

**Comment by maikvandergaag** [comment]
Could you share more information? Extension should publish everything in the pbix file

**Comment by arnabdasgupta04** [comment]
Ideally while publishing any pbix file the below 3 files gets published 
![image](https://user-images.githubusercontent.com/63199431/141967503-0a56c4e0-909f-49c4-a25c-79ba21a3d4b9.png)

But while using the extension the below 2 files are getting published from the pbix file.
![image](https://user-images.githubusercontent.com/63199431/141967635-6d4645bf-8578-4ccb-89b4-09ee224d2308.png)

The dashboard with .pbix extension is missing .

Is there any other way to upload the dashboard , though this is not an issue but thought of clarifying my doubt.

**Comment by maikvandergaag** [comment]
Once we have time we will check how we can accommodate.

**Comment by mattias-de-coninck** [comment]
@arnabdasgupta04  The REST APIs does not seem to allow for the creation of a dashboard when uploading a PBIX file. This also makes sense to me because the use-case for dashboard is to display visuals from multiple reports. Hence, when uploading a single PBIX file, there should be no scenario where you want to turn the report into a dashboard 1 to 1.
